export const BUSQUEDA_POKENAME = "BUSQUEDA_POKENAME"
export const BUSQUEDA_AMPLIA = "BUSQUEDA_AMPLIA"
export const SET_TYPES= "SET_TYPES"
export const ADD_POKEMONS= "ADD_POKEMONS"
export const SET_PUNTEROS= "SET_PUNTEROS"
export const SET_ID_PK= "SET_ID_PK"




